#!/bin/bash

if [ -f ".ssh/id_rsa"];
then
	echo "An RSA key already exists in '.ssh'"
	echo "Exiting"
fi

ssh-keygen -f .ssh/id_rsa -N "" -C HeroHub
heroku keys:add .ssh/id_rsa.pub
heroku apps:create
git push heroku HEAD

echo "Setup Successful"